name: "Staging Environment"

on: 
  push:
    branches: 
      - v2/staging
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v2 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      
      - name: Build application
        env:
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: npm run build

      - name: Restart server app
        run: pm2 restart strapi
